learning_rate: 0.001
name: entnet_qa_w_gt

concat_history: false

model:
  encoder: 'entnetqa'
  decoder: 'lstm'
  
  max_seq_len: 16
  num_blocks: 100
  word_embedding_size: 30
  rnn_hidden_size: 256
  rnn_num_layers: 2
  dropout: 0.2