learning_rate: 0.001
name: entnet

concat_history: false

model:
  model: 'roundwise'
  encoder: 'entnet'
  decoder: 'lstm'
  
  max_seq_len: 17
  num_blocks: 100
  word_embedding_size: 30
  rnn_hidden_size: 256
  rnn_num_layers: 2
  dropout: 0.2
