learning_rate: 0.001
name: simple_lstm
concat_history: true

model:
  model: "enc2dec"
  encoder: 'lstm'
  decoder: 'lstm'
  
  max_seq_len: 17
  word_embedding_size: 30
  rnn_hidden_size: 256
  rnn_num_layers: 2
  dropout: 0.2
