learning_rate: 0.001
name: memnn_qa_w_inf_dis

concat_history: false

model:
  encoder: 'memnnqa'
  inference_encoder: 'memnn'
  inference_decoder: 'lstm'
  inference_path: './output/memnn/checkpoint_best.pth'
  max_seq_len: 17
  word_embedding_size: 30
  rnn_hidden_size: 256
  rnn_num_layers: 2
  dropout: 0.2
