learning_rate: 0.001
name: memnn_gen

concat_history: false

model:
  model: 'enc2dec'
  encoder: 'memnn'
  decoder: 'gen'
  
  max_seq_len: 17
  word_embedding_size: 30
  rnn_hidden_size: 256
  rnn_num_layers: 2
  dropout: 0.2
